// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoaZ6ewG3O_Sz7Ue1dWD24L0COPn_Ualw',
    appId: '1:751857329071:web:af8159761d90c4cca9055a',
    messagingSenderId: '751857329071',
    projectId: 'edtapp-2e807',
    authDomain: 'edtapp-2e807.firebaseapp.com',
    storageBucket: 'edtapp-2e807.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7uoRRQxivWgZtF8O8wASnIXBg1jGvTV8',
    appId: '1:751857329071:android:a1ef0b2c7f346096a9055a',
    messagingSenderId: '751857329071',
    projectId: 'edtapp-2e807',
    storageBucket: 'edtapp-2e807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXmr6EqlTrs1hVb8M4k9I-eAqcshUpHI',
    appId: '1:751857329071:ios:fba882698a500f56a9055a',
    messagingSenderId: '751857329071',
    projectId: 'edtapp-2e807',
    storageBucket: 'edtapp-2e807.firebasestorage.app',
    iosBundleId: 'com.example.edt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXmr6EqlTrs1hVb8M4k9I-eAqcshUpHI',
    appId: '1:751857329071:ios:fba882698a500f56a9055a',
    messagingSenderId: '751857329071',
    projectId: 'edtapp-2e807',
    storageBucket: 'edtapp-2e807.firebasestorage.app',
    iosBundleId: 'com.example.edt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoaZ6ewG3O_Sz7Ue1dWD24L0COPn_Ualw',
    appId: '1:751857329071:web:f049bf3eb3e87b0da9055a',
    messagingSenderId: '751857329071',
    projectId: 'edtapp-2e807',
    authDomain: 'edtapp-2e807.firebaseapp.com',
    storageBucket: 'edtapp-2e807.firebasestorage.app',
  );

}