// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk3Mdp55nfMiK0EasBB45LSNxWJ5BQ0Hc',
    appId: '1:836416174419:web:7bd079e01ab4c7dee9c9a6',
    messagingSenderId: '836416174419',
    projectId: 'edt-app',
    authDomain: 'edt-app.firebaseapp.com',
    storageBucket: 'edt-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8zKE0XRTm4BhdagzNe00fEaaS35AbbuM',
    appId: '1:836416174419:android:a4c2f80446778030e9c9a6',
    messagingSenderId: '836416174419',
    projectId: 'edt-app',
    storageBucket: 'edt-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSCG4pAytrrwhixNR7OsIUtH6ys7W6fQc',
    appId: '1:836416174419:ios:81a05824ad5ffb60e9c9a6',
    messagingSenderId: '836416174419',
    projectId: 'edt-app',
    storageBucket: 'edt-app.firebasestorage.app',
    iosBundleId: 'com.example.edt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSCG4pAytrrwhixNR7OsIUtH6ys7W6fQc',
    appId: '1:836416174419:ios:81a05824ad5ffb60e9c9a6',
    messagingSenderId: '836416174419',
    projectId: 'edt-app',
    storageBucket: 'edt-app.firebasestorage.app',
    iosBundleId: 'com.example.edt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk3Mdp55nfMiK0EasBB45LSNxWJ5BQ0Hc',
    appId: '1:836416174419:web:fb548d3b0441b0cee9c9a6',
    messagingSenderId: '836416174419',
    projectId: 'edt-app',
    authDomain: 'edt-app.firebaseapp.com',
    storageBucket: 'edt-app.firebasestorage.app',
  );
}
